packages:
  - packages/core
  - packages/runway
  - packages/rpc
  - packages/controller
  - packages/utils
  - packages/demo
  - packages/bootstrap
  - packages/create-proxy-app

overrides:
  htmlparser2: 12.0.0
  
catalog:
  "@mercuryworkshop/wisp-js": 0.4.1
  "@mercuryworkshop/proxy-transports": 1.0.2
  "@mercuryworkshop/libcurl-transport": 2.0.5
  "@mercuryworkshop/epoxy-transport": 3.0.1
  htmlparser2: 12.0.0

patchedDependencies:
  htmlparser2@12.0.0: patches/htmlparser2@12.0.0.patch