packages:
  - "packages/core"
  - "packages/bootstrap"
  - "packages/controller"
  - "packages/scramjetserver"
  - "packages/bare-mux-custom"
  - "packages/epoxy-transport"
  - "packages/libcurl-transport"
  - "packages/demo"
  - "packages/rewriter_demo"
  - "packages/typedoc"
